### ISSUE TITLE
Help With Configuration

### ISSUE THREAD

**Issue by bradlis7** [idleberg/atom-build-lessc#2]
I can't seem to figure this out based on the readme page. Do I need to add something to my `.atom-build.yml` file, or should it automatically show up in targets? Maybe something changed in the build package that's not been updated on this project? There isn't enough info for this to be useful.

**Comment by idleberg** [comment]
Did the package work for you at some point? There was a recent change in `isEligible()`, but I haven't noticed any problems.

You don't need a build file, but afaik `build` only works with projects. And –obviously– you need `lessc` installed.

**Comment by idleberg** [comment]
Actually, I found a bug. Please update and let me know if the problem persists.

**Comment by bradlis7** [comment]
I guess I didn't understand what the configuration is saying, so this is more of a documentation issue to me. I was trying to use it with atom-build, but your instructions says put the configuration in "config.caml", whereas atom-build says to use ".atom-build.yaml" (or .caml). I don't know what "config.caml" is referring to, and couldn't find any reference to it in the atom interface.

I've moved back to the more simpler "less-autocompile" for my needs for now. I was looking to make it so that if I edited a dependent .less file, then it would compile the appropriate parent(s), but I might have to use something like gulp to achieve that.

**Comment by idleberg** [comment]
Build files are a feature provided by the `build` plugin, they can be YAML, JSON, CSON or a JavaScript file containing an object. Those let you specify a build command without the need of installing an additional provider.

The settings for this `lessc` build provider are stored in the Atom's default `config.json` (or `config.cson`). In our case, it  let's you specify your preferred naming schema for the output file.
